package com.parasoft.demoapp.retrofitConfig;

import java.util.Objects;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

public class PDAService {

    private static String baseUrl = null;
    private static String authToken = null;
    private static Retrofit retrofit = null;

    public static synchronized <T> T getClient(Class<T> serviceClass) {
        if(retrofit == null) {
            refreshRetrofit();
        }

        return retrofit.create(serviceClass);
    }

    public static void refreshRetrofit() {
        retrofit = new Retrofit.Builder()
                    .baseUrl(baseUrl)
                    .addConverterFactory(GsonConverterFactory.create())
                    .client(getOkHttpClient())
                    .build();
    }

    private static OkHttpClient getOkHttpClient() {
        OkHttpClient.Builder httpClientBuilder = new OkHttpClient.Builder();

        httpClientBuilder.addInterceptor(chain -> {
            Request request = chain.request()
                    .newBuilder()
                    .removeHeader("User-Agent") // Remove the original User-Agent header of generated by okhttp
                    .addHeader("User-Agent", Objects.requireNonNull(System.getProperty("http.agent")))
                    .build();
            return chain.proceed(request);
        });

        if (authToken != null) {
            httpClientBuilder.addInterceptor(chain -> {
                Request request = chain.request()
                        .newBuilder()
                        .header("Authorization", authToken)
                        .build();
                return chain.proceed(request);
            });
        }

        return httpClientBuilder.build();
    }

    public static void setBaseUrl(String baseUrl) {
        PDAService.baseUrl = baseUrl;
        refreshRetrofit();
    }

    public static void setAuthToken(String authToken) {
        PDAService.authToken = authToken;
        refreshRetrofit();
    }
}
